; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
lib_deps =
  sui77/rc-switch @ ^2.6.4

[env:esp32doit-devkit-v1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32doit-devkit-v1
framework = arduino
build_flags =
  -DSWITCH_TX_PIN=27
  -DSWITCH_RX_PIN=34


monitor_speed = 115200
monitor_echo = yes
monitor_eol = CRLF

[env:waveshare_esp32_s3_zero]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = waveshare_esp32_s3_zero
framework = arduino
build_flags =
  -DSWITCH_TX_PIN=1
  -DSWITCH_RX_PIN=5
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200
monitor_echo = yes
monitor_eol = CRLF